import { createHash, randomUUID } from "node:crypto";
import { link, open, unlink } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { z } from "zod";
import {
  ImmutableJsonArtifactStore,
  assertArtifactReference,
  type ArtifactReference,
} from "../../artifact-store/src/index.js";
import { contentHash, stableJson } from "../../contracts/src/index.js";
import { assertBoundedGameJson } from "../../game-ir/src/primitives.js";
import { DEFAULT_GAME_ADMISSION_POLICY } from "../../game-ir/src/index.js";
import {
  AssetError,
  AssetRegistry,
  assertCubeJobIntent,
  createCubeJobIntent,
  ensureAssetDirectory,
  fitAssetGeometry,
  inspectObj,
  readPinnedAssetFile,
  parseCubeGeneration,
  validateAssetSpec,
  type AssetLock,
  type CubeJobIntent,
  type CubeGeneration,
} from "./index.js";
import {
  runCubeJob,
  creatorCubeInstallationFingerprint,
  validateCubeInstallation,
  verifyCubeInputPin,
  type CreatorCubeInstallation,
} from "./cube-worker.js";
import {
  remoteCubeConfigSchema,
  runRemoteCubeJob,
  probeRemoteCube,
  validateRemoteIntent,
  fetchRemoteCubeOutput,
  validateRemoteEvidence,
  validateCubePartInputBytes,
  cubeRemoteJob,
  type RemoteCubeInstallation,
} from "./cube-remote.js";
import {
  createCompositionBinding,
  parseCompositionPin,
  parseCompositionPins,
  type ReviewedAssetCompositionResolution,
  type ReviewedAssetCompositionCatalog,
} from "./composition.js";
import { createMeshReview } from "./mesh-review.js";
import { writeMeshReviewHtml } from "./mesh-review-html.js";

const sha256 = z.string().regex(/^[a-f0-9]{64}$/);
const positiveInteger = z.number().int().positive().safe();
const pinSchema = z
  .object({ path: z.string().min(1).max(512), sha256, bytes: positiveInteger })
  .strict();
const policySchema = z
  .object({
    timeoutMs: positiveInteger.max(2147483647),
    maximumLogBytes: positiveInteger.max(16 * 1024 * 1024),
    maximumInputBytes: positiveInteger.max(64 * 1024 * 1024 * 1024),
    maximumOutputBytes: positiveInteger.max(16 * 1024 * 1024),
  })
  .strict();
const localInstallationSchema = z
  .object({
    kind: z.literal("CreatorCubeInstallation"),
    cube: z
      .object({
        kind: z.enum(["cube_local", "recorded_fixture"]),
        executable: z.string().min(1).max(4096),
        root: z.string().min(1).max(4096),
        codeFiles: z.array(pinSchema).min(1).max(4096),
        configuration: pinSchema,
        gptCheckpoint: pinSchema,
        shapeCheckpoint: pinSchema,
        license: z.string().min(1).max(2048),
      })
      .strict(),
    executablePin: z.object({ sha256, bytes: positiveInteger.max(512 * 1024 * 1024) }).strict(),
    policy: policySchema,
  })
  .strict();
const installationSchema = z.union([
  localInstallationSchema,
  z
    .object({
      kind: z.literal("CreatorCubeInstallation"),
      cube: remoteCubeConfigSchema,
      policy: policySchema,
    })
    .strict(),
]);

interface PreparedAssetJob {
  kind: "CreatorAssetPreparation";
  jobId: string;
  preparedAt: string;
  intent: CubeJobIntent;
  installation: CreatorCubeInstallation;
}
interface AssetJobOutcome {
  kind: "CreatorAssetOutcome";
  jobId: string;
  preparation: ArtifactReference;
  status: "locally_inspected" | "recovery_required";
  reason?: string;
  failureCode?: string;
  lock?: ArtifactReference;
  workerReceipt?: ArtifactReference;
  diagnostic?: ArtifactReference;
  executionOutcome?: ArtifactReference;
  sourceHash?: string;
  origin: "worker" | "explicit_output_reconciliation";
}
export interface CreatorAssetJobStatus {
  kind: "CreatorAssetJobStatus";
  jobId: string;
  assetId: string;
  storeDirectory: string;
  artifactDirectory: string;
  executionDirectory: string;
  status: "prepared" | "dispatched" | "recovery_required" | "locally_inspected" | "reviewed";
  preparation: ArtifactReference;
  dispatch?: ArtifactReference;
  outcome?: ArtifactReference;
  executionOutcome?: ArtifactReference;
  reconciliation?: ArtifactReference;
  review?: ArtifactReference;
  diagnostic?: ArtifactReference;
  workerReceipt?: ArtifactReference;
  lock?: AssetLock;
  lockArtifact?: ArtifactReference;
  reason?: string;
  failureCode?: string;
  mayRun: boolean;
  nativeReadiness: "unavailable";
  limitations: string[];
  composition?: ReviewedAssetCompositionResolution;
}
const LIMITATIONS = [
  "Preparation and review concern local generated bytes only. Roblox import, ownership, moderation, permissions, collision, rendering and persistence remain unavailable.",
  "A dispatch is consumed once. Missing or uncertain completion requires explicit output reconciliation; status never authorizes a blind rerun.",
  "The pinned subprocess has time/log/output limits, not an OS memory, disk or network sandbox.",
];
const referenceSchema = z
  .object({ locator: z.string(), artifactHash: sha256, bytes: positiveInteger })
  .strict();
const outcomeSchema = z
  .object({
    kind: z.literal("CreatorAssetOutcome"),
    jobId: z.string(),
    preparation: referenceSchema,
    status: z.enum(["locally_inspected", "recovery_required"]),
    reason: z.string().max(8192).optional(),
    failureCode: z.string().min(1).max(128).optional(),
    lock: referenceSchema.optional(),
    workerReceipt: referenceSchema.optional(),
    diagnostic: referenceSchema.optional(),
    executionOutcome: referenceSchema.optional(),
    sourceHash: sha256.optional(),
    origin: z.enum(["worker", "explicit_output_reconciliation"]),
  })
  .strict();
const capturedLogSchema = z
  .object({
    encoding: z.literal("base64"),
    content: z.string().max(4 * Math.ceil((16 * 1024 * 1024) / 3)),
    sha256,
    bytes: z
      .number()
      .int()
      .min(0)
      .max(16 * 1024 * 1024),
  })
  .strict();
const diagnosticSchema = z
  .object({
    kind: z.literal("CubeJobDiagnostic"),
    intentHash: sha256,
    installationKind: z.enum(["cube_local", "recorded_fixture", "cube_remote"]),
    installationHash: sha256,
    status: z.enum(["locally_inspected", "recovery_required"]),
    failureCode: z.enum(["intent_consumed", "execution_incomplete", "output_rejected"]).optional(),
    reason: z.string().min(1).max(8192).optional(),
    remote: referenceSchema.optional(),
    execution: z
      .object({
        stdout: capturedLogSchema,
        stderr: capturedLogSchema,
        logsTruncated: z.boolean(),
        exitCode: z.number().int().safe().nullable(),
        signal: z.string().min(1).max(128).nullable(),
        reason: z.string().min(1).max(8192).optional(),
      })
      .strict()
      .optional(),
  })
  .strict();
const hostDiagnosticSchema = z
  .object({
    kind: z.literal("CreatorAssetHostDiagnostic"),
    intentHash: sha256,
    installationKind: z.enum(["cube_local", "recorded_fixture", "cube_remote"]),
    installationHash: sha256,
    failureCode: z.string().min(1).max(128),
    reason: z.string().min(1).max(8192),
    workerDiagnostic: referenceSchema.optional(),
  })
  .strict();
const receiptSchema = z
  .object({
    kind: z.literal("CubeJobLocalReceipt"),
    intentHash: sha256,
    installationKind: z.enum(["cube_local", "recorded_fixture", "cube_remote"]),
    installationHash: sha256,
    assetLock: sha256,
    sourceHash: sha256,
    exitCode: z.literal(0),
    diagnostic: referenceSchema,
    claims: z.literal(
      "Local byte inspection only; no Roblox upload, native import, rendering, permissions or collision evidence.",
    ),
  })
  .strict();

/** Durable creator preparation, consumed through the `creator asset` CLI. No native writes. */
export class CreatorAssetJobs {
  readonly root: string;
  readonly store: ImmutableJsonArtifactStore;
  constructor(root: string) {
    this.root = resolve(root);
    // JSON escaping can expand a bounded OBJ. The raw geometry budget stays at 16 MiB.
    this.store = new ImmutableJsonArtifactStore(join(this.root, "evidence"), {
      maxBytes: 40 * 1024 * 1024,
    });
  }

  async prepare(request: unknown, hostInstallation: unknown): Promise<CreatorAssetJobStatus> {
    assertBoundedGameJson(request, DEFAULT_GAME_ADMISSION_POLICY);
    if (
      !request ||
      typeof request !== "object" ||
      Array.isArray(request) ||
      "id" in request ||
      "provenance" in request
    )
      throw new AssetError(
        "invalid_request",
        "Creator asset requests cannot supply asset identities or provenance",
      );
    const installation = parseCreatorCubeInstallation(hostInstallation);
    const { generation: requestedGeneration, ...assetRequest } = request as Record<string, unknown>;
    const spec = validateAssetSpec({
      ...assetRequest,
      id: "asset-" + randomUUID().replaceAll("-", ""),
    });
    const generation = await this.prepareGeneration(requestedGeneration);
    const pins = isRemote(installation)
      ? installation.cube
      : {
          codeHash: contentHash(
            stableJson(
              [...installation.cube.codeFiles].sort((a, b) =>
                a.path < b.path ? -1 : a.path > b.path ? 1 : 0,
              ),
            ),
          ),
          configurationHash: installation.cube.configuration.sha256,
          checkpointHashes: [
            installation.cube.gptCheckpoint.sha256,
            installation.cube.shapeCheckpoint.sha256,
          ],
        };
    const intent = createCubeJobIntent({
      spec,
      generation,
      codeHash: pins.codeHash,
      configurationHash: pins.configurationHash,
      checkpointHashes: pins.checkpointHashes,
    });
    await verifyHostInstallation(installation, intent);
    if (isRemote(installation))
      await cubeRemoteJob(intent, installation, new AssetRegistry(this.store));
    const prepared: PreparedAssetJob = {
      kind: "CreatorAssetPreparation",
      jobId: intent.jobId,
      preparedAt: new Date().toISOString(),
      intent,
      installation,
    };
    await this.writeStage(intent.jobId, "preparation", prepared);
    return this.status(intent.jobId);
  }

  async run(jobId: string, signal?: AbortSignal): Promise<CreatorAssetJobStatus> {
    const loaded = await this.prepared(jobId);
    const existing = await this.status(jobId);
    if (!existing.mayRun) return existing;
    // Published before verification/launch: any later exception is retained as a consumed attempt.
    try {
      await this.writeStage(jobId, "dispatch", {
        kind: "CreatorAssetDispatch",
        jobId,
        preparation: loaded.reference,
        dispatchedAt: new Date().toISOString(),
      });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EEXIST") return this.status(jobId);
      throw error;
    }
    let outcome: AssetJobOutcome;
    let workerDiagnostic: ArtifactReference | undefined;
    try {
      await verifyHostInstallation(loaded.value.installation, loaded.value.intent);
      const workerInput = {
        intent: loaded.value.intent,
        registry: new AssetRegistry(this.store),
        jobRoot: join(this.root, "executions"),
        ...(signal ? { signal } : {}),
      };
      const result = isRemote(loaded.value.installation)
        ? await runRemoteCubeJob({ ...workerInput, installation: loaded.value.installation })
        : await runCubeJob({ ...workerInput, installation: loaded.value.installation });
      workerDiagnostic = result.diagnostic;
      await verifyExecutable(loaded.value.installation);
      outcome =
        result.status === "locally_inspected"
          ? {
              kind: "CreatorAssetOutcome",
              jobId,
              preparation: loaded.reference,
              status: "locally_inspected",
              lock: await this.store.write(result.lock),
              workerReceipt: result.receipt,
              diagnostic: result.diagnostic,
              sourceHash: result.lock.sourceHash,
              origin: "worker",
            }
          : {
              kind: "CreatorAssetOutcome",
              jobId,
              preparation: loaded.reference,
              status: "recovery_required",
              reason: result.reason,
              failureCode: result.failureCode,
              diagnostic: result.diagnostic,
              origin: "worker",
            };
    } catch (error) {
      const reason = error instanceof Error ? error.message.slice(0, 8192) : "Asset worker failed";
      const failureCode = error instanceof AssetError ? error.code : "host_operation_failed";
      outcome = {
        kind: "CreatorAssetOutcome",
        jobId,
        preparation: loaded.reference,
        status: "recovery_required",
        reason,
        failureCode,
        diagnostic: await this.store.write({
          kind: "CreatorAssetHostDiagnostic",
          intentHash: loaded.value.intent.hash,
          installationKind: loaded.value.installation.cube.kind,
          installationHash: creatorCubeInstallationFingerprint(loaded.value.installation),
          reason,
          failureCode,
          ...(workerDiagnostic ? { workerDiagnostic } : {}),
        }),
        origin: "worker",
      };
    }
    await this.writeStage(jobId, "result", outcome);
    return this.status(jobId);
  }

  /** Explicit remote GET recovery; never starts inference or erases the original attempt. */
  async fetch(
    jobId: string,
    signal?: AbortSignal,
  ): Promise<{
    kind: "CreatorAssetRemoteFetch";
    jobId: string;
    status: string;
    evidence: ArtifactReference;
    sourceHash?: string;
  }> {
    const loaded = await this.prepared(jobId);
    const current = await this.status(jobId);
    if (!current.dispatch || !isRemote(loaded.value.installation))
      throw new AssetError("invalid_state", "Fetch requires a dispatched remote job");
    const fetched = await fetchRemoteCubeOutput({
      intent: loaded.value.intent,
      installation: loaded.value.installation,
      registry: new AssetRegistry(this.store),
      jobRoot: join(this.root, "executions"),
      ...(signal ? { signal } : {}),
    });
    return {
      kind: "CreatorAssetRemoteFetch",
      jobId,
      status: fetched.receipt.status,
      evidence: fetched.evidence,
      ...(fetched.sourceHash ? { sourceHash: fetched.sourceHash } : {}),
    };
  }

  private async prepareGeneration(input: unknown): Promise<CubeGeneration> {
    if (input === undefined) return parseCubeGeneration({ operation: "cube3d", seed: 0 });
    if (
      !input ||
      typeof input !== "object" ||
      !("operation" in input) ||
      input.operation !== "cubepart"
    )
      return parseCubeGeneration(input);
    const requested = z
      .object({
        operation: z.literal("cubepart"),
        seed: z.number().int().min(0).max(2147483647),
        input: pinSchema,
        parts: z
          .array(z.object({ id: z.string(), prompt: z.string() }).strict())
          .min(1)
          .max(8),
      })
      .strict()
      .parse(input);
    const absolute = resolve(requested.input.path);
    const bytes = await readPinnedAssetFile(
      dirname(absolute),
      basename(absolute),
      Math.min(requested.input.bytes, 16 * 1024 * 1024),
    );
    if (
      bytes.length !== requested.input.bytes ||
      createHash("sha256").update(bytes).digest("hex") !== requested.input.sha256
    )
      throw new AssetError("hash_mismatch", "CubePart input differs from its declared file pin");
    validateCubePartInputBytes(bytes);
    const sourceArtifact = await this.store.write({
      kind: "RecordedObjBytes",
      sourceHash: requested.input.sha256,
      utf8Bytes: bytes.length,
      obj: new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(bytes),
    });
    return parseCubeGeneration({
      ...requested,
      input: { sourceArtifact, sha256: requested.input.sha256, bytes: bytes.length },
    });
  }

  /** Snapshot an explicitly identified preserved output. This neither relaunches nor asserts job success. */
  async reconcile(jobId: string, expectedSourceHash: string): Promise<CreatorAssetJobStatus> {
    sha256.parse(expectedSourceHash);
    const loaded = await this.prepared(jobId);
    const current = await this.status(jobId);
    if (!current.dispatch)
      throw new AssetError(
        "invalid_state",
        "An undispatched preparation has no output to reconcile",
      );
    if (current.lock) {
      if (current.lock.sourceHash !== expectedSourceHash)
        throw new AssetError("hash_mismatch", "The existing inspected output has a different hash");
      return current;
    }
    const bytes = await readPinnedAssetFile(
      this.root,
      `executions/${jobId}/output/output.obj`,
      loaded.value.installation.policy.maximumOutputBytes,
    );
    const lock = await new AssetRegistry(this.store).ingestRecordedObj({
      bytes,
      expectedSourceHash,
      spec: loaded.value.intent.spec,
      provenance: provenanceFor(loaded.value, true),
    });
    const outcome: AssetJobOutcome = {
      kind: "CreatorAssetOutcome",
      jobId,
      preparation: loaded.reference,
      status: "locally_inspected",
      lock: await this.store.write(lock),
      sourceHash: lock.sourceHash,
      origin: "explicit_output_reconciliation",
      ...(current.executionOutcome ? { executionOutcome: current.executionOutcome } : {}),
    };
    await this.writeStage(jobId, "reconciliation", outcome);
    return this.status(jobId);
  }

  /** CLI invocation is the creator's explicit review of these exact local bytes/fit, never native approval. */
  async review(jobId: string, expectedLockHash: string): Promise<CreatorAssetJobStatus> {
    sha256.parse(expectedLockHash);
    const current = await this.status(jobId);
    if (!current.lock || current.lock.hash !== expectedLockHash)
      throw new AssetError(
        "hash_mismatch",
        "Review requires the current exact inspected lock hash",
      );
    if (current.review) return current;
    const reviewDecision = {
      kind: "CreatorAssetReview",
      jobId,
      preparation: current.preparation,
      outcome: current.outcome!,
      lock: current.lockArtifact!,
      lockHash: expectedLockHash,
      reviewedAt: new Date().toISOString(),
      scope: "local_bytes_and_fit_only",
    };
    const composition = await this.store.write(
      createCompositionBinding({
        jobId,
        reviewDecision,
        preparation: current.preparation,
        outcome: current.outcome!,
        lockArtifact: current.lockArtifact!,
        lock: current.lock,
      }),
    );
    await this.writeStage(jobId, "review", { ...reviewDecision, composition });
    return this.status(jobId);
  }

  /** Replays recorded source and its lock; creating a view never marks an asset reviewed. */
  async preview(jobId: string, outputPath: string) {
    const current = await this.status(jobId);
    if (!current.lock)
      throw new AssetError(
        "invalid_record",
        "A geometry preview requires a completed, locally inspected asset",
      );
    const source = await this.store.read<{ kind: string; obj: string }>(
      current.lock.sourceArtifact,
    );
    if (source.kind !== "RecordedObjBytes" || typeof source.obj !== "string")
      throw new AssetError("invalid_record", "Asset source record is malformed");
    const data = createMeshReview({ bytes: Buffer.from(source.obj, "utf8"), lock: current.lock });
    return {
      kind: "CreatorAssetPreview" as const,
      jobId,
      status: current.status,
      lockHash: current.lock.hash,
      reviewHash: data.hash,
      artifact: await writeMeshReviewHtml(outputPath, data),
      nativeReadiness: "unavailable" as const,
    };
  }

  async status(jobId: string): Promise<CreatorAssetJobStatus> {
    const loaded = await this.prepared(jobId);
    const dispatch = await this.readStage(jobId, "dispatch");
    if (dispatch) {
      const data = z
        .object({
          kind: z.literal("CreatorAssetDispatch"),
          jobId: z.literal(jobId),
          preparation: referenceSchema,
          dispatchedAt: z.string().datetime(),
        })
        .strict()
        .parse(await this.store.read(dispatch));
      sameReference(data.preparation, loaded.reference);
    }
    const reconciliation = await this.readStage(jobId, "reconciliation");
    const executionOutcome = await this.readStage(jobId, "result");
    const outcomeRef = reconciliation ?? executionOutcome;
    if (outcomeRef && !dispatch)
      throw new AssetError("invalid_record", "Output record lacks its dispatch intent");
    // Replay the original attempt even when explicit reconciliation supplies the selected output.
    const executed = executionOutcome
      ? await this.readOutcome(executionOutcome, loaded, "worker")
      : undefined;
    const reconciled = reconciliation
      ? await this.readOutcome(reconciliation, loaded, "explicit_output_reconciliation")
      : undefined;
    if (reconciled?.outcome.executionOutcome) {
      if (!executionOutcome)
        throw new AssetError(
          "invalid_record",
          "Reconciliation lost its original execution outcome",
        );
      sameReference(reconciled.outcome.executionOutcome, executionOutcome);
    }
    const selected = reconciled ?? executed;
    const outcome = selected?.outcome;
    const lock = selected?.lock;
    const review = await this.readStage(jobId, "review");
    let composition: ReviewedAssetCompositionResolution | undefined;
    if (review) {
      const data = z
        .object({
          kind: z.literal("CreatorAssetReview"),
          jobId: z.literal(jobId),
          preparation: referenceSchema,
          outcome: referenceSchema,
          lock: referenceSchema,
          lockHash: sha256,
          reviewedAt: z.string().datetime(),
          scope: z.literal("local_bytes_and_fit_only"),
          composition: referenceSchema,
        })
        .strict()
        .parse(await this.store.read(review));
      if (!lock || !outcomeRef || !outcome?.lock || data.lockHash !== lock.hash)
        throw new AssetError("invalid_record", "Review lacks matching inspected output");
      sameReference(data.preparation, loaded.reference);
      sameReference(data.outcome, outcomeRef);
      sameReference(data.lock, outcome.lock);
      const { composition: bindingArtifact, ...reviewDecision } = data;
      const binding = createCompositionBinding({
        jobId,
        reviewDecision,
        preparation: loaded.reference,
        outcome: outcomeRef,
        lockArtifact: outcome.lock,
        lock,
      });
      if (stableJson(await this.store.read(bindingArtifact)) !== stableJson(binding))
        throw new AssetError(
          "hash_mismatch",
          "Reviewed asset composition binding differs from its exact review and source",
        );
      composition = { binding, bindingArtifact, review };
    }
    return {
      kind: "CreatorAssetJobStatus",
      jobId,
      assetId: loaded.value.intent.spec.id,
      storeDirectory: this.root,
      artifactDirectory: this.store.root,
      executionDirectory: join(this.root, "executions", jobId),
      status: review ? "reviewed" : (outcome?.status ?? (dispatch ? "dispatched" : "prepared")),
      preparation: loaded.reference,
      ...(dispatch ? { dispatch } : {}),
      ...(outcomeRef ? { outcome: outcomeRef } : {}),
      ...(executionOutcome ? { executionOutcome } : {}),
      ...(reconciliation ? { reconciliation } : {}),
      ...(review ? { review } : {}),
      ...(executed?.outcome.diagnostic ? { diagnostic: executed.outcome.diagnostic } : {}),
      ...(executed?.outcome.workerReceipt ? { workerReceipt: executed.outcome.workerReceipt } : {}),
      ...(lock && outcome?.lock ? { lock, lockArtifact: outcome.lock } : {}),
      ...(outcome?.reason
        ? { reason: outcome.reason }
        : dispatch && !outcome
          ? {
              reason:
                "The consumed dispatch has no completion record. It may still be running or interrupted; reconcile preserved output instead of rerunning.",
            }
          : {}),
      ...(outcome?.failureCode
        ? { failureCode: outcome.failureCode }
        : dispatch && !outcome
          ? { failureCode: "completion_unrecorded" }
          : {}),
      mayRun: !dispatch && !outcomeRef && !review,
      nativeReadiness: "unavailable",
      limitations: [...LIMITATIONS],
      ...(composition ? { composition } : {}),
    };
  }

  /** Reopens exact reviewed host evidence; arbitrary asset IDs/URLs never enter this resolver. */
  async resolveCompositionAsset(input: unknown): Promise<ReviewedAssetCompositionResolution> {
    const pin = parseCompositionPin(input);
    const status = await this.status(pin.jobId);
    if (!status.composition || !status.review || !status.lock)
      throw new AssetError(
        "review_required",
        "Asset composition requires an explicit review of exact local bytes",
      );
    if (
      pin.assetId !== status.assetId ||
      pin.lockHash !== status.lock.hash ||
      pin.reviewHash !== status.review.artifactHash
    )
      throw new AssetError("hash_mismatch", "Composition pin differs from the reviewed host asset");
    if (pin.universeId !== status.lock.spec.universeId)
      throw new AssetError("universe_mismatch", "Composition pin targets another universe");
    return status.composition;
  }

  /** Trusted callers choose a bounded exact inventory; this does not enumerate files or grant native readiness. */
  async catalogCompositionAssets(input: unknown): Promise<ReviewedAssetCompositionCatalog> {
    const pins = parseCompositionPins(input);
    if (
      new Set(pins.map((pin) => pin.jobId)).size !== pins.length ||
      new Set(pins.map((pin) => pin.assetId)).size !== pins.length
    )
      throw new AssetError(
        "duplicate_id",
        "Composition catalog requires distinct exact asset jobs",
      );
    const assets: ReviewedAssetCompositionResolution[] = [];
    for (const pin of [...pins].sort((a, b) =>
      a.assetId < b.assetId ? -1 : a.assetId > b.assetId ? 1 : 0,
    ))
      assets.push(await this.resolveCompositionAsset(pin));
    const value = { kind: "ReviewedAssetCompositionCatalog" as const, assets };
    assertBoundedGameJson(value as unknown, DEFAULT_GAME_ADMISSION_POLICY);
    return { ...value, hash: contentHash(stableJson(value)) };
  }

  private async readOutcome(
    reference: ArtifactReference,
    prepared: { reference: ArtifactReference; value: PreparedAssetJob },
    origin: AssetJobOutcome["origin"],
  ): Promise<{ outcome: z.infer<typeof outcomeSchema>; lock?: AssetLock }> {
    const outcome = outcomeSchema.parse(await this.store.read(reference));
    if (outcome.jobId !== prepared.value.jobId || outcome.origin !== origin)
      throw new AssetError("invalid_record", "Outcome identity or stage origin mismatch");
    sameReference(outcome.preparation, prepared.reference);
    if (origin === "explicit_output_reconciliation") {
      if (outcome.status !== "locally_inspected" || outcome.workerReceipt || outcome.diagnostic)
        throw new AssetError(
          "invalid_record",
          "Reconciliation cannot assert worker execution evidence",
        );
    } else {
      if (outcome.executionOutcome)
        throw new AssetError(
          "invalid_record",
          "Worker outcome cannot replace its execution history",
        );
      if (!outcome.diagnostic)
        throw new AssetError("invalid_record", "Worker outcome lacks its diagnostic artifact");
      const raw = await this.store.read<{ kind?: unknown }>(outcome.diagnostic);
      if (raw.kind === "CreatorAssetHostDiagnostic") {
        const diagnostic = hostDiagnosticSchema.parse(raw);
        this.bindDiagnostic(diagnostic, prepared.value);
        if (
          outcome.status !== "recovery_required" ||
          diagnostic.reason !== outcome.reason ||
          diagnostic.failureCode !== outcome.failureCode
        )
          throw new AssetError("invalid_record", "Host diagnostic does not match failed outcome");
        if (diagnostic.workerDiagnostic)
          await this.readWorkerDiagnostic(diagnostic.workerDiagnostic, prepared.value);
      } else {
        const diagnostic = await this.readWorkerDiagnostic(outcome.diagnostic, prepared.value);
        if (
          diagnostic.status !== outcome.status ||
          diagnostic.reason !== outcome.reason ||
          diagnostic.failureCode !== outcome.failureCode
        )
          throw new AssetError("invalid_record", "Worker diagnostic does not match outcome");
      }
    }
    if (outcome.status === "recovery_required") {
      if (
        outcome.lock ||
        outcome.sourceHash ||
        outcome.workerReceipt ||
        !outcome.reason ||
        !outcome.failureCode
      )
        throw new AssetError(
          "invalid_record",
          "Failed outcome cannot grant an asset lock or success receipt",
        );
      return { outcome };
    }
    if (!outcome.lock || !outcome.sourceHash || outcome.reason || outcome.failureCode)
      throw new AssetError(
        "invalid_record",
        "Inspected outcome lacks exact output references or asserts failure",
      );
    const lock = await this.readLock(
      outcome.lock,
      prepared.value,
      origin === "explicit_output_reconciliation",
    );
    if (lock.sourceHash !== outcome.sourceHash)
      throw new AssetError("hash_mismatch", "Outcome source hash mismatch");
    if (origin === "worker") {
      if (!outcome.workerReceipt)
        throw new AssetError(
          "invalid_record",
          "Inspected worker outcome lacks its success receipt",
        );
      const receipt = receiptSchema.parse(await this.store.read(outcome.workerReceipt));
      this.bindDiagnostic(receipt, prepared.value);
      if (receipt.assetLock !== lock.hash || receipt.sourceHash !== lock.sourceHash)
        throw new AssetError("hash_mismatch", "Worker receipt does not bind the inspected output");
      sameReference(receipt.diagnostic, outcome.diagnostic!);
      if (isRemote(prepared.value.installation)) {
        const diagnostic = await this.readWorkerDiagnostic(outcome.diagnostic!, prepared.value);
        const remote = await validateRemoteEvidence(
          diagnostic.remote!,
          prepared.value.intent,
          prepared.value.installation,
          new AssetRegistry(this.store),
        );
        if (
          remote.result?.output?.sha256 !== lock.sourceHash ||
          remote.result.output.bytes !== lock.sourceUtf8Bytes
        )
          throw new AssetError(
            "hash_mismatch",
            "Inspected mesh differs from the remote execution output",
          );
      }
    }
    return { outcome, lock };
  }

  private bindDiagnostic(
    value: { intentHash: string; installationKind: string; installationHash: string },
    prepared: PreparedAssetJob,
  ): void {
    if (
      value.intentHash !== prepared.intent.hash ||
      value.installationKind !== prepared.installation.cube.kind ||
      value.installationHash !== creatorCubeInstallationFingerprint(prepared.installation)
    )
      throw new AssetError(
        "hash_mismatch",
        "Worker evidence does not bind this job intent and installation",
      );
  }

  private async readWorkerDiagnostic(
    reference: ArtifactReference,
    prepared: PreparedAssetJob,
  ): Promise<z.infer<typeof diagnosticSchema>> {
    const diagnostic = diagnosticSchema.parse(await this.store.read(reference));
    this.bindDiagnostic(diagnostic, prepared);
    if (isRemote(prepared.installation)) {
      if (diagnostic.execution)
        throw new AssetError(
          "invalid_record",
          "Remote diagnostics use their bound remote execution receipt",
        );
      const remote = diagnostic.remote
        ? await validateRemoteEvidence(
            diagnostic.remote,
            prepared.intent,
            prepared.installation,
            new AssetRegistry(this.store),
          )
        : undefined;
      if (diagnostic.status === "locally_inspected") {
        if (remote?.status !== "succeeded" || diagnostic.reason || diagnostic.failureCode)
          throw new AssetError(
            "invalid_record",
            "Inspected remote output lacks its matching successful execution",
          );
      } else if (
        !diagnostic.reason ||
        !diagnostic.failureCode ||
        (diagnostic.failureCode === "intent_consumed" && remote) ||
        (diagnostic.failureCode === "output_rejected" && remote?.status !== "succeeded")
      )
        throw new AssetError("invalid_record", "Remote failure contradicts its recorded outcome");
      return diagnostic;
    }
    if (diagnostic.remote)
      throw new AssetError("invalid_record", "Local execution cannot supply a remote receipt");
    const execution = diagnostic.execution;
    if (execution) {
      let bytes = 0;
      for (const log of [execution.stdout, execution.stderr]) {
        const content = Buffer.from(log.content, "base64");
        bytes += content.length;
        if (
          content.length !== log.bytes ||
          content.toString("base64") !== log.content ||
          createHash("sha256").update(content).digest("hex") !== log.sha256
        )
          throw new AssetError("hash_mismatch", "Captured worker log bytes or hash mismatch");
      }
      if (
        bytes > prepared.installation.policy.maximumLogBytes ||
        (execution.logsTruncated && bytes !== prepared.installation.policy.maximumLogBytes)
      )
        throw new AssetError(
          "invalid_record",
          "Captured worker logs exceed or misstate their allowance",
        );
      if (
        execution.reason === undefined &&
        (execution.exitCode !== 0 || execution.signal !== null || execution.logsTruncated)
      )
        throw new AssetError(
          "invalid_record",
          "Worker execution success contradicts termination evidence",
        );
    }
    if (diagnostic.status === "locally_inspected") {
      if (
        !execution ||
        execution.reason !== undefined ||
        diagnostic.reason !== undefined ||
        diagnostic.failureCode !== undefined
      )
        throw new AssetError(
          "invalid_record",
          "Successful worker diagnostic requires completed execution",
        );
    } else {
      if (!diagnostic.reason || !diagnostic.failureCode)
        throw new AssetError("invalid_record", "Failed worker diagnostic lacks its classification");
      if (
        diagnostic.failureCode === "intent_consumed"
          ? execution !== undefined
          : execution === undefined
      )
        throw new AssetError(
          "invalid_record",
          "Worker failure classification contradicts execution presence",
        );
      if (
        diagnostic.failureCode === "execution_incomplete" &&
        execution?.reason !== diagnostic.reason
      )
        throw new AssetError(
          "invalid_record",
          "Interrupted worker diagnostic lacks its exact execution reason",
        );
      if (diagnostic.failureCode === "output_rejected" && execution?.reason !== undefined)
        throw new AssetError(
          "invalid_record",
          "Output rejection requires completed worker execution",
        );
    }
    return diagnostic;
  }

  private async prepared(
    jobId: string,
  ): Promise<{ reference: ArtifactReference; value: PreparedAssetJob }> {
    assertJobId(jobId);
    const reference = await this.readStage(jobId, "preparation");
    if (!reference)
      throw new AssetError(
        "unknown_job",
        "No creator asset preparation has this host-issued job ID",
      );
    const value = await this.store.read<PreparedAssetJob>(reference);
    assertBoundedGameJson(value as unknown, {
      ...DEFAULT_GAME_ADMISSION_POLICY,
      maximumJsonBytes: 4 * 1024 * 1024,
    });
    if (
      Object.keys(value).sort().join(",") !== "installation,intent,jobId,kind,preparedAt" ||
      value.kind !== "CreatorAssetPreparation" ||
      value.jobId !== jobId ||
      value.intent.jobId !== jobId ||
      !Number.isFinite(Date.parse(value.preparedAt))
    )
      throw new AssetError("invalid_record", "Malformed creator asset preparation");
    assertCubeJobIntent(value.intent);
    parseCreatorCubeInstallation(value.installation);
    return { reference, value };
  }

  private async readLock(
    reference: ArtifactReference,
    prepared: PreparedAssetJob,
    reconciled: boolean,
  ): Promise<AssetLock> {
    const lock = await this.store.read<AssetLock>(reference);
    assertBoundedGameJson(lock as unknown, DEFAULT_GAME_ADMISSION_POLICY);
    const { hash, ...body } = lock;
    if (
      hash !== contentHash(stableJson(body)) ||
      lock.kind !== "AssetLock" ||
      lock.assetId !== prepared.intent.spec.id ||
      stableJson(lock.spec) !== stableJson(prepared.intent.spec) ||
      stableJson(lock.provenance) !== stableJson(provenanceFor(prepared, reconciled)) ||
      lock.readiness !== "locally_inspected" ||
      lock.permissions.status !== "unverified" ||
      lock.permissions.universeId !== prepared.intent.spec.universeId ||
      lock.dependencies.length !== 0
    )
      throw new AssetError(
        "invalid_record",
        "Asset lock does not match this preparation's local-only authority",
      );
    const source = await this.store.read<{
      kind: string;
      sourceHash: string;
      utf8Bytes: number;
      obj: string;
    }>(lock.sourceArtifact);
    if (source.kind !== "RecordedObjBytes" || typeof source.obj !== "string")
      throw new AssetError("invalid_record", "Asset source record is malformed");
    const bytes = Buffer.from(source.obj, "utf8");
    if (
      bytes.byteLength !== lock.sourceUtf8Bytes ||
      source.utf8Bytes !== bytes.byteLength ||
      source.sourceHash !== lock.sourceHash ||
      createHash("sha256").update(bytes).digest("hex") !== lock.sourceHash
    )
      throw new AssetError("hash_mismatch", "Stored OBJ byte hash mismatch");
    const geometry = inspectObj(bytes);
    if (
      stableJson(geometry) !== stableJson(lock.geometry) ||
      stableJson(fitAssetGeometry(geometry, validateAssetSpec(lock.spec))) !== stableJson(lock.fit)
    )
      throw new AssetError("hash_mismatch", "Stored asset inspection or fit mismatch");
    return lock;
  }

  private async readStage(jobId: string, stage: string): Promise<ArtifactReference | undefined> {
    assertJobId(jobId);
    let bytes: Buffer;
    try {
      bytes = await readPinnedAssetFile(this.root, `records/${jobId}/${stage}.json`, 2048);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
      throw error;
    }
    const reference: unknown = JSON.parse(bytes.toString("utf8"));
    assertArtifactReference(reference);
    return reference;
  }

  private async writeStage(
    jobId: string,
    stage: string,
    value: unknown,
  ): Promise<ArtifactReference> {
    assertJobId(jobId);
    const reference = await this.store.write(value);
    const directory = await ensureAssetDirectory(join(this.root, "records", jobId));
    const temporary = join(directory, ".stage-" + randomUUID());
    const handle = await open(temporary, "wx", 0o600);
    try {
      await handle.writeFile(stableJson(reference) + "\n");
      await handle.sync();
    } finally {
      await handle.close();
    }
    try {
      await link(temporary, join(directory, stage + ".json"));
    } finally {
      await unlink(temporary);
    }
    return reference;
  }
}

function assertJobId(jobId: string): void {
  if (!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(jobId))
    throw new AssetError("invalid_identity", "Asset job IDs are host-issued UUIDs");
}
function sameReference(actual: ArtifactReference, expected: ArtifactReference): void {
  assertArtifactReference(actual);
  if (stableJson(actual) !== stableJson(expected))
    throw new AssetError("hash_mismatch", "Creator asset record reference mismatch");
}
export function parseCreatorCubeInstallation(input: unknown): CreatorCubeInstallation {
  assertBoundedGameJson(input, {
    ...DEFAULT_GAME_ADMISSION_POLICY,
    maximumJsonBytes: 4 * 1024 * 1024,
  });
  return installationSchema.parse(input);
}
async function verifyExecutable(installation: CreatorCubeInstallation): Promise<void> {
  if (isRemote(installation)) return;
  await verifyCubeInputPin(dirname(installation.cube.executable), {
    path: basename(installation.cube.executable),
    ...installation.executablePin,
  });
}
async function verifyHostInstallation(
  installation: CreatorCubeInstallation,
  intent: CubeJobIntent,
): Promise<void> {
  if (isRemote(installation)) {
    validateRemoteIntent(installation, intent);
    await probeRemoteCube(installation);
    return;
  }
  await validateCubeInstallation(installation.cube, intent, installation.policy);
  await verifyExecutable(installation);
}
function provenanceFor(prepared: PreparedAssetJob, reconciled = false): AssetLock["provenance"] {
  return {
    kind:
      reconciled || prepared.installation.cube.kind === "recorded_fixture"
        ? "recorded_obj"
        : prepared.installation.cube.kind,
    source: (reconciled ? "creator-output-reconciliation:" : "") + prepared.intent.hash,
    license: prepared.installation.cube.license,
    codeHash: prepared.intent.codeHash,
    configurationHash: prepared.intent.configurationHash,
    checkpointHashes: prepared.intent.checkpointHashes,
  };
}
function isRemote(installation: CreatorCubeInstallation): installation is RemoteCubeInstallation {
  return installation.cube.kind === "cube_remote";
}
export async function probeCreatorCubeInstallation(input: unknown): Promise<unknown> {
  const installation = parseCreatorCubeInstallation(input);
  if (isRemote(installation)) return probeRemoteCube(installation);
  await verifyExecutable(installation);
  return {
    kind: "CubeLocalProbe",
    status: "executable_pin_matched",
    installationHash: creatorCubeInstallationFingerprint(installation),
    claims: "Executable bytes only; prepare verifies the remaining model and code pins",
  };
}

/** CLI JSON inputs remain bounded regular files, never model-authored executable options. */
export async function readCreatorAssetInput(path: string): Promise<unknown> {
  const absolute = resolve(path);
  return JSON.parse(
    (await readPinnedAssetFile(dirname(absolute), basename(absolute), 4 * 1024 * 1024)).toString(
      "utf8",
    ),
  ) as unknown;
}
