import type { GameBuildControlView } from "../../../packages/creator-conversation/src/game-build-contract";
const HASH = "a".repeat(64);
/** Canvas acceptance data only. These concepts are never imported by production code. */
const SHOWCASE_CONCEPTS = [
  [
    "leaderboard",
    "Leaderboard",
    "Compare the achievements of players across the world.",
    "🏆",
    undefined,
  ],
  ["rating", "Rating", "Track growth and unlock new challenges through play.", "⭐", undefined],
  ["morph", "Morph", "Take on different forms to explore and play.", "🦋", undefined],
  ["wins", "Wins", "Victories earned through completed challenges.", "⚔️", "leaderboard"],
  ["time", "Time played", "Time spent exploring the world.", "⏱️", "leaderboard"],
  ["streak", "Streak", "Consecutive successful challenges.", "🔥", "leaderboard"],
  ["levels", "Levels", "Milestones reached as players improve.", "📈", "rating"],
  ["rewards", "Rewards", "Items earned at each milestone.", "🎁", "rating"],
  ["progress", "Progress", "Progress toward the next milestone.", "📊", "rating"],
  ["wolf", "Wolf", "A form built for traveling with a pack.", "🐺", "morph"],
  ["dragon", "Dragon", "A form that takes exploration into the sky.", "🐉", "morph"],
  ["fox", "Fox", "A nimble form for finding hidden routes.", "🦊", "morph"],
  ["bronze", "Bronze", "The first level of mastery.", "🥉", "levels"],
  ["silver", "Silver", "The next level of mastery.", "🥈", "levels"],
  ["gold", "Gold", "A milestone for experienced players.", "🥇", "levels"],
] as const;
export const GRAPH_VIEW: GameBuildControlView = {
  components: [
    { id: "scene", kind: "recipe_instance", observedSources: 0 },
    { id: "logic", kind: "source_package", observedSources: 0 },
  ],
  componentDependencies: [{ from: "logic", to: "scene" }],
  planHash: HASH,
  graphHash: "b".repeat(64),
  status: "stopped",
  architecture: {
    name: "Shared workshop",
    nodes: [
      {
        id: "construction",
        name: "Building surfaces",
        description: "Places where players assemble and change their creations.",
        componentIds: ["scene"],
        operationIds: ["root", "part"],
        status: "stopped",
        appliedOperations: 1,
      },
      {
        id: "interaction",
        name: "Tool interactions",
        description: "Connects player actions to changes in the shared workshop.",
        componentIds: ["logic"],
        operationIds: ["script"],
        status: "stopped",
        appliedOperations: 0,
      },
    ],
    relationships: [
      { id: "edit", from: "interaction", to: "construction", label: "Edits surfaces" },
    ],
  },
  stoppedReason: "Connection lost before checkpoint 2. The first checkpoint remains applied.",
  nodes: [
    {
      id: "root",
      componentId: "scene",
      label: "Workshop",
      path: "Workspace/Workshop",
      className: "Folder",
      operation: "create",
      status: "applied",
      provenance: {
        componentKind: "recipe_instance",
        definitionId: "scene.primitives",
        definitionHash: HASH,
      },
      lockedProperties: {},
      valueSlots: [],
    },
    {
      id: "script",
      componentId: "logic",
      label: "Controller",
      path: "Workspace/Workshop/Controller",
      className: "ModuleScript",
      operation: "create",
      status: "stopped",
      provenance: { componentKind: "source_package" },
      source: { fileId: "controller", kind: "slot", maximumUtf8Bytes: 2048 },
      lockedProperties: {},
      valueSlots: [],
    },
    {
      id: "part",
      componentId: "scene",
      label: "Worktop",
      path: "Workspace/Workshop/Worktop",
      className: "Part",
      operation: "create",
      status: "stopped",
      provenance: {
        componentKind: "recipe_instance",
        definitionId: "scene.primitives",
        definitionHash: HASH,
      },
      lockedProperties: { Anchored: { type: "boolean", value: true } },
      valueSlots: [{ id: "color", propertyName: "Color", schema: { type: "object" } }],
    },
  ],
  edges: [
    { from: "script", to: "root", kind: "parent" },
    { from: "part", to: "root", kind: "parent" },
    { from: "script", to: "part", kind: "dependency" },
  ],
  partitions: [
    { id: "first", ordinal: 0, status: "applied", nodeIds: ["root"], receiptHash: HASH },
    { id: "second", ordinal: 1, status: "stopped", nodeIds: ["script", "part"] },
  ],
  receipts: [{ partitionId: "first", hash: HASH, status: "verified" }],
};
export const MAP_SHOWCASE: GameBuildControlView = {
  ...GRAPH_VIEW,
  architecture: {
    name: "The Wilds",
    icon: "🌍",
    nodes: SHOWCASE_CONCEPTS.map(([id, name, description, icon, parentId]) => ({
      id,
      name,
      description,
      icon,
      ...(parentId ? { parentId } : {}),
      componentIds: ["logic"],
      operationIds: ["script"],
      status: "stopped",
      appliedOperations: 0,
    })),
    relationships: [
      { id: "growth", from: "morph", to: "rating", label: "Earns progress" },
      { id: "ranking", from: "rating", to: "leaderboard", label: "Ranks players" },
    ],
  },
};
